/**
 * @page misc Miscellaneous files
 *
 * Misc files.
 *
 * | File            | Description            |
 * | :-------------- | :--------------------- |
 * | addrbook.c      | @subpage addrbook      |
 * | complete.c      | @subpage complete      |
 * | compress.c      | @subpage compress      |
 * | copy.c          | @subpage copy          |
 * | editmsg.c       | @subpage editmsg       |
 * | enter.c         | @subpage enter         |
 * | filter.c        | @subpage filter        |
 * | flags.c         | @subpage flags         |
 * | hook.c          | @subpage hook          |
 * | main.c          | @subpage main          |
 * | mutt_account.c  | @subpage mutt_account  |
 * | mutt_logging.c  | @subpage mutt_logging  |
 * | mutt_signal.c   | @subpage mutt_signal   |
 * | mutt_socket.c   | @subpage mutt_socket   |
 * | mutt_window.c   | @subpage window        |
 * | mx.c            | @subpage mx            |
 * | postpone.c      | @subpage postpone      |
 * | progress.c      | @subpage progress      |
 * | resize.c        | @subpage resize        |
 * | rfc1524.c       | @subpage rfc1524       |
 * | safe_asprintf.c | @subpage safe_asprintf |
 * | sidebar.c       | @subpage sidebar       |
 * | status.c        | @subpage status        |
 * | system.c        | @subpage system        |
 * | terminal.c      | @subpage terminal      |
 * | version.c       | @subpage version       |
 */
